### ISSUE TITLE
LogmanConfig.txt has incorrect entry for Broker Activation perfmon counters

### ISSUE THREAD

**Issue by NathanMSFT** [microsoft/SQL_LogScout#13]
LogmanConfig.txt that gets created shows:

\MSSQL$SQL2022:Broker Activation\*

It needs to be:

\MSSQL$SQL2022:Broker Activation(*)\*

There are multiple instances (per database) of that counter, so the ‘(*)’ needs to be added before the backslash.

I suggest checking for additional discrepancies between the way LogmanConfig.txt gets created and if there are other problems with counters not getting collected due to bad definition in LogmanConfig.txt.

**Comment by PiJoCoder** [comment]
Thanks for reporting. This is now fixed in an internal build and will be shipped in up-coming release
