### ISSUE TITLE
Add support/integration for SQL Nexus to analyze the logs collected by Logscout

### ISSUE THREAD

**Issue by sandykools** [microsoft/SQL_LogScout#16]
We cannot analyze all the required parameter or logs collected by this tool using SQL Nexus. for an example, Polybase errors. Can you please add integration to SQLNexus or provide a tool for analyzing the Logscout output.

**Comment by JamesFerebee** [comment]
@sandykools the ingestion of data sets into SQLNexus is managed in that project and not here. Please look at filing items at https://github.com/microsoft/SqlNexus for specific scenarios and what data you are looking to consume.

I'd like to set expectations that we generally try to implement reports/collectors for the most impactful scenarios so depending on the scope of the work and expected impact, it may be better to build a local solution that looks at the specific logscout data you are looking to review.
