### ISSUE TITLE
The WPR scenario does not work on Server 2019/2016. No etl file is generated  with this scenario due to unsupported param to WPR.exe

### ISSUE THREAD

**Issue by cleng-ms** [microsoft/SQL_LogScout#6]
On Server 2019/2016, when I use the WPR scenario, not ETL file is generated at the end. The cause of the problem is that LogScout is passing the -skipPdbGen option to WPR.exe, and this option is not supported in the in-box version of WPR.exe on Server 2019/2016. Below is a simple test on my Server 2019 VM. The -skippdbgen option causes an error and no traces are collected due to this error.

---------------
C:\temp\SQL_LogScout_v4.5_Signed>wpr.exe -start DiskIO -start FileIO -filemode

C:\temp\SQL_LogScout_v4.5_Signed>wpr.exe -stop "C:\temp\SQL_LogScout_v4.5_Signed\output\no_instance_found_20221018T0935081095_WPR_DiskIO_FileIO.etl" -skippdbgen

        Invalid command syntax.

        Error code: 0xc5600602

        Stops WPR recording and merges all the recording into the given file
        wpr -stop <recording filename> <Problem description>
---------------

The problem is in SQLLogScoutPs.ps1
------------------
        #stop WPR trace
        if ($true -eq (IsScenarioEnabled -scenarioBit $global:wprBit ))
        {
            Stop-WPRTrace -partial_error_output_file_name $partial_error_output_file_name " -skippdbgen"
        }
------------------

**Comment by cleng-ms** [comment]
The SkipPDBGen is first added in Win10 2004.
https://learn.microsoft.com/en-us/windows-hardware/get-started/what-s-new-in-kits-and-tools
ADK for Windows 10, version 2004
Windows Performance Recorder (WPR)
New SkipPDBGen Option - During WPR stop, you can now specify in the command line the ability to skip generation of PDBs (NGen & Embedded) to help reduce trace stop time.

How about checking the version of wpr.exe and then decide if we add the " -skippdbgen" option or not depending on the version? We can get the version of wpr.exe in the following way.

**PS C:\> $WprPath=where.exe wpr.exe
PS C:\> [System.Diagnostics.FileVersionInfo]::GetVersionInfo($WprPath).FileVersion
10.0.17763.2989 (WinBuild.160101.0800)**

**Comment by PiJoCoder** [comment]
@cleng-ms thank you for reporting this. We will address in next version.

**Comment by JamesFerebee** [comment]
@cleng-ms Thank you for raising this. We have coded a fix for this behavior and will be included in the next released version.

Thanks for your feedback and improving LogScout.
