### ISSUE TITLE
Gather log files for SQL Server - Azure Arc extension as a new scenario

### ISSUE THREAD

**Issue by suresh-kandoth** [microsoft/SQL_LogScout#8]
The log files for the extension and agent are located in different folders under C drive. Examples:
C:\Program Files\AzureConnectedMachineAgent\
C:\ProgramData\AzureConnectedMachineAgent\
C:\Packages\Plugins\Microsoft.AzureData.WindowsAgent.SqlServer\
C:\ProgramData\GuestConfig\

We should add this as a new scenario and gather the relevant logs from these folders related to the extension and agent,
Also, there is some information in Event viewer and possibly registry that we need to collect.

**Comment by PiJoCoder** [comment]
We have implemented a call to Azcmagent.exe  logs -o c:\temp\azcmagent-sqllogscout.zip -f which will gather all the Azure Arc Enable SQL Server logs.
